name: CI

on: [push, pull_request]

jobs:
  lint:
    strategy:
      matrix:
        node: ['14', '16', '18']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.1.1
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm run lint
  test:
    strategy:
      matrix:
        node: ['14', '16', '18']
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.1.1
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm test